title: Minimalist theme
logo: /assets/img/logo.png
email: bogus at gmail dot com
description: Minimalist is a theme powered by Jekyll. It is modified based on the Minimal theme.
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sidebar:
  - name: Google Scholar
    icon: fa-solid fa-user-graduate
    link: https://scholar.google.com/citations?user=zR6afi8AAAAJ
  - name: GitHub
    icon: fa-brands fa-github
    link: https://github.com/BDHU
  - name: Twitter
    icon: fa-brands fa-twitter
    link: https://twitter.com/BodunHu
  - name: Blog
    icon: fa-solid fa-pen
    link: https://www.bodunhu.com/blog/
  - name: Project Repository
    icon: fa-solid fa-box-archive
    link: https://github.com/BDHU/minimalist
