title: Minimalist theme
description: Minimalist is a theme powered by Jekyll. It is modified based on the Minimal theme.
show_downloads: false
google_analytics: UA-108144808-1
theme: jekyll-theme-minimalist
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
